In [1]:
from cayman_office_system import *

INFO:shining_pebbles:Shining Pebbles package initialized
INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
/Users/juneyoungpark/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [4]:
trade = Trade()

| import trade of (date, index) = (2024-10-11, -1)
|- cash flow of trade: -341436216.0

In [6]:
trade.raw

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,"9th Fl. Samsung Electronics Bldg.,",NaN,NaN,NaN,NaN,NaN,NaN
2,"11, 74-gil Seocho-daero Seocho-gu, Seoul 06620,",NaN,NaN,NaN,NaN,NaN,NaN
3,Republic of Korea,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,Please notify us by email (middle.st@samsung.c...,NaN,NaN,NaN,NaN,NaN,NaN
80,in this confirmation by 5pm (Korea time) on th...,NaN,NaN,NaN,NaN,NaN,NaN
81,Note we shall not be liable for any indirect o...,NaN,NaN,NaN,NaN,NaN,NaN
82,incurred in respect of this transaction.,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
transactions = trade.transactions

In [9]:
transaction = transactions[0]

In [11]:
transaction.df

               ticker num_shares currency  price_executed      amount
date
2024-10-11  007340 KS        500   /  KRW         18440.0   9220000.0
2024-10-11  007340 KS          1   /  KRW         18450.0     18450.0
2024-10-11  007340 KS         39   /  KRW         18460.0    719940.0
2024-10-11  007340 KS        500   /  KRW         18470.0   9235000.0
2024-10-11  007340 KS        100   /  KRW         18490.0   1849000.0
2024-10-11  007340 KS        336   /  KRW         18500.0   6216000.0
2024-10-11  007340 KS        740   /  KRW         18510.0  13697400.0
2024-10-11  007340 KS        680   /  KRW         18520.0  12593600.0
2024-10-11  007340 KS         64   /  KRW         18530.0   1185920.0
2024-10-11  007340 KS         80   /  KRW         18540.0   1483200.0
2024-10-11  007340 KS        176   /  KRW         18550.0   3264800.0
2024-10-11  007340 KS        364   /  KRW         18570.0   6759480.0
2024-10-11  007340 KS        697   /  KRW         18580.0  12950260.0
2024-10-11  007340 KS        523   /  KRW         18590.0   9722570.0
2024-10-11  007340 KS        200   /  KRW         18650.0   3730000.0

In [12]:
transaction.data

{'date': '2024-10-11',
 'name': 'DN AUTOMOTIVE',
 'ticker': '007340 KS',
 'type': 'Buy',
 'num_shares': 5000,
 'average_price': 18529.124,
 'consideration': 92645620.0,
 'commission': 92646,
 'net_amount': 92738266.0}