In [1]:
from cayman_office_system import *

INFO:shining_pebbles:Shining Pebbles package initialized
INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.
/Users/juneyoungpark/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py:60: UserWarning: Pandas requires version '1.3.6' or newer of 'bottleneck' (version '1.3.5' currently installed).
  from pandas.core import (

In [3]:
trades = Trades()

- import trade of (date, index) = (2024-09-02, None)
- net_amount: 614581438.0
- import trade of (date, index) = (2024-09-05, None)
- net_amount: 529470241.0
- import trade of (date, index) = (2024-09-06, None)
- net_amount: 91060069.0
- import trade of (date, index) = (2024-09-09, None)
- net_amount: 384482599.0
- import trade of (date, index) = (2024-09-10, None)
- net_amount: 625076151.0
- import trade of (date, index) = (2024-09-12, None)
- net_amount: 528686258.0
- import trade of (date, index) = (2024-09-13, None)
- net_amount: 519691172.0
- import trade of (date, index) = (2024-09-19, None)
- net_amount: 727234488.0
- import trade of (date, index) = (2024-09-20, None)
- net_amount: 1931465216.0
- import trade of (date, index) = (2024-09-23, None)
- net_amount: 726876600.0
- import trade of (date, index) = (2024-09-24, None)
- net_amount: 1282227226.0
- import trade of (date, index) = (2024-09-26, None)
- net_amount: 405884829.0

In [5]:
lkef = CaymanFund(trades=trades)

In [8]:
df_nav = lkef.get_timeseries_nav()
df_nav

,nav_krw,nav_usd,price_krw,price_usd,return_krw,return_usd,cumreturn_krw,cumreturn_usd
date,,,,,,,,
2024-09-01,2.050955e+10,1.533081e+07,1000.000000,1000.000000,0.000000,0.000000,0.000000,0.000000
2024-09-02,2.051594e+10,1.532928e+07,1000.311587,999.900505,0.031159,-0.009950,0.031159,-0.009950
2024-09-03,2.058266e+10,1.533845e+07,1003.564665,1000.498404,0.325206,0.059796,0.356466,0.049840
2024-09-04,2.056874e+10,1.532807e+07,1002.885713,999.821527,-0.067654,-0.067654,0.288571,-0.017847
2024-09-05,2.046552e+10,1.533515e+07,997.853107,1000.283157,-0.501812,0.046171,-0.214689,0.028316
2024-09-06,2.046317e+10,1.532822e+07,997.738703,999.831338,-0.011465,-0.045169,-0.226130,-0.016866
2024-09-07,2.046317e+10,1.532822e+07,997.738703,999.831338,0.000000,0.000000,-0.226130,-0.016866
2024-09-08,2.046317e+10,1.532822e+07,997.738703,999.831338,0.000000,0.000000,-0.226130,-0.016866
2024-09-09,2.048584e+10,1.534520e+07,998.843925,1000.938878,0.110773,0.110773,-0.115608,0.093888
2024-09-10,2.055091e+10,1.529086e+07,1002.016513,997.394115,0.317626,-0.354144,0.201651,-0.260589
2024-09-11,2.052352e+10,1.531263e+07,1000.681073,998.814548,-0.133275,0.142414,0.068107,-0.118545
2024-09-12,2.061588e+10,1.536206e+07,1005.184335,1002.038453,0.450020,0.322773,0.518434,0.203845
2024-09-13,2.045972e+10,1.534230e+07,997.570257,1000.749496,-0.757481,-0.128633,-0.242974,0.074950
2024-09-14,2.045972e+10,1.534230e+07,997.570257,1000.749496,0.000000,0.000000,-0.242974,0.074950
2024-09-15,2.045972e+10,1.534230e+07,997.570257,1000.749496,0.000000,0.000000,-0.242974,0.074950
2024-09-16,2.045972e+10,1.534230e+07,997.570257,1000.749496,0.000000,0.000000,-0.242974,0.074950
2024-09-17,2.045972e+10,1.534230e+07,997.570257,1000.749496,0.000000,0.000000,-0.242974,0.074950
2024-09-18,2.045972e+10,1.534230e+07,997.570257,1000.749496,0.000000,0.000000,-0.242974,0.074950
2024-09-19,2.045380e+10,1.538979e+07,997.281828,1003.847583,-0.028913,0.309577,-0.271817,0.384758
2024-09-20,2.068064e+10,1.548880e+07,1008.341933,1010.305450,1.109025,0.643312,0.834193,1.030545
2024-09-21,2.068064e+10,1.548880e+07,1008.341933,1010.305450,0.000000,0.000000,0.834193,1.030545
2024-09-22,2.068064e+10,1.548880e+07,1008.341933,1010.305450,0.000000,0.000000,0.834193,1.030545
2024-09-23,2.071227e+10,1.551190e+07,1009.883946,1011.812577,0.152926,0.149175,0.988395,1.181258
2024-09-24,2.072492e+10,1.556743e+07,1010.501029,1015.434745,0.061104,0.357988,1.050103,1.543475
2024-09-25,2.075575e+10,1.554156e+07,1012.004208,1013.747083,0.148756,-0.166201,1.200421,1.374708
2024-09-26,2.075678e+10,1.575647e+07,1012.054466,1027.765183,0.004966,1.382801,1.205447,2.776518
2024-09-27,2.071125e+10,1.580348e+07,1009.834366,1030.831647,-0.219366,0.298362,0.983437,3.083165
2024-09-28,2.071125e+10,1.580348e+07,1009.834366,1030.831647,0.000000,0.000000,0.983437,3.083165
2024-09-29,2.071125e+10,1.580348e+07,1009.834366,1030.831647,0.000000,0.000000,0.983437,3.083165
2024-09-30,2.057608e+10,1.565078e+07,1003.243655,1020.871197,-0.652653,-0.966254,0.324366,2.087120
2024-10-01,2.057608e+10,1.565078e+07,1003.243655,1020.871197,0.000000,0.000000,0.324366,2.087120
2024-10-02,2.056610e+10,1.554564e+07,1002.757165,1014.013028,-0.048492,-0.671796,0.275717,1.401303
2024-10-03,2.056610e+10,1.554564e+07,1002.757165,1014.013028,0.000000,0.000000,0.275717,1.401303

In [9]:
df_nav.to_csv(f'dataset-lkef-nav-save{get_today()}.csv')

In [12]:
df_weight = lkef.timeseries
df_weight

,cash_usd,cash_krw,stock_usd,stock_krw,nav_usd,nav_krw,weight_cash_usd,weight_stock_usd,weight_cash_krw,weight_stock_krw
date,,,,,,,,,,
2024-09-01,1.533081e+07,2.050955e+10,0.000000e+00,0.000000e+00,1.533081e+07,2.050955e+10,100.000000,0.000000,100.000000,0.000000
2024-09-02,1.487160e+07,1.990340e+10,4.576830e+05,6.125400e+08,1.532928e+07,2.051594e+10,97.014322,2.985678,97.014322,2.985678
2024-09-03,1.487160e+07,1.995620e+10,4.668492e+05,6.264650e+08,1.533845e+07,2.058266e+10,96.956346,3.043654,96.956346,3.043654
2024-09-04,1.487160e+07,1.995620e+10,4.564722e+05,6.125400e+08,1.532807e+07,2.056874e+10,97.021985,2.978015,97.021985,2.978015
2024-09-05,1.447486e+07,1.931742e+10,8.602900e+05,1.148100e+09,1.533515e+07,2.046552e+10,94.390077,5.609923,94.390077,5.609923
2024-09-06,1.440665e+07,1.923287e+10,9.215730e+05,1.230300e+09,1.532822e+07,2.046317e+10,93.987736,6.012264,93.987736,6.012264
2024-09-07,1.440665e+07,1.923287e+10,9.215730e+05,1.230300e+09,1.532822e+07,2.046317e+10,93.987736,6.012264,93.987736,6.012264
2024-09-08,1.440665e+07,1.923287e+10,9.215730e+05,1.230300e+09,1.532822e+07,2.046317e+10,93.987736,6.012264,93.987736,6.012264
2024-09-09,1.411865e+07,1.884839e+10,1.226554e+06,1.637450e+09,1.534520e+07,2.048584e+10,92.006918,7.993082,92.006918,7.993082
2024-09-10,1.365356e+07,1.835038e+10,1.637297e+06,2.200527e+09,1.529086e+07,2.055091e+10,89.292314,10.707686,89.292314,10.707686
2024-09-11,1.365356e+07,1.829987e+10,1.659073e+06,2.223656e+09,1.531263e+07,2.052352e+10,89.165330,10.834670,89.165330,10.834670
2024-09-12,1.325961e+07,1.779439e+10,2.102452e+06,2.821491e+09,1.536206e+07,2.061588e+10,86.313993,13.686007,86.313993,13.686007
2024-09-13,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-14,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-15,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-16,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-17,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-18,1.286990e+07,1.716266e+10,2.472397e+06,3.297064e+09,1.534230e+07,2.045972e+10,83.885095,16.114905,83.885095,16.114905
2024-09-19,1.232272e+07,1.637751e+10,3.067076e+06,4.076298e+09,1.538979e+07,2.045380e+10,80.070711,19.929289,80.070711,19.929289
2024-09-20,1.087614e+07,1.452183e+10,4.612654e+06,6.158816e+09,1.548880e+07,2.068064e+10,70.219415,29.780585,70.219415,29.780585
2024-09-21,1.087614e+07,1.452183e+10,4.612654e+06,6.158816e+09,1.548880e+07,2.068064e+10,70.219415,29.780585,70.219415,29.780585
2024-09-22,1.087614e+07,1.452183e+10,4.612654e+06,6.158816e+09,1.548880e+07,2.068064e+10,70.219415,29.780585,70.219415,29.780585
2024-09-23,1.033177e+07,1.379549e+10,5.180135e+06,6.916775e+09,1.551190e+07,2.071227e+10,66.605420,33.394580,66.605420,33.394580
2024-09-24,9.368629e+06,1.247246e+10,6.198805e+06,8.252469e+09,1.556743e+07,2.072492e+10,60.180946,39.819054,60.180946,39.819054
2024-09-25,9.368629e+06,1.251180e+10,6.172932e+06,8.243950e+09,1.554156e+07,2.075575e+10,60.281134,39.718866,60.281134,39.718866
2024-09-26,9.060522e+06,1.193588e+10,6.695947e+06,8.820906e+09,1.575647e+07,2.075678e+10,57.503503,42.496497,57.503503,42.496497
2024-09-27,9.060522e+06,1.187427e+10,6.742959e+06,8.836985e+09,1.580348e+07,2.071125e+10,57.332445,42.667555,57.332445,42.667555
2024-09-28,9.060522e+06,1.187427e+10,6.742959e+06,8.836985e+09,1.580348e+07,2.071125e+10,57.332445,42.667555,57.332445,42.667555
2024-09-29,9.060522e+06,1.187427e+10,6.742959e+06,8.836985e+09,1.580348e+07,2.071125e+10,57.332445,42.667555,57.332445,42.667555
2024-09-30,9.060522e+06,1.191187e+10,6.590257e+06,8.664211e+09,1.565078e+07,2.057608e+10,57.891827,42.108173,57.891827,42.108173
2024-10-01,9.060522e+06,1.191187e+10,6.590257e+06,8.664211e+09,1.565078e+07,2.057608e+10,57.891827,42.108173,57.891827,42.108173
2024-10-02,9.060522e+06,1.198662e+10,6.485116e+06,8.579484e+09,1.554564e+07,2.056610e+10,58.283372,41.716628,58.283372,41.716628
2024-10-03,9.060522e+06,1.198662e+10,6.485116e+06,8.579484e+09,1.554564e+07,2.056610e+10,58.283372,41.716628,58.283372,41.716628

In [14]:
df_weight.to_csv(f'dataset-lkef-weight-save{get_today()}.csv')

In [18]:
df_holdings = lkef.holdings.pl
df_holdings

,name,num_shares,net_amount,evaluation,pl,price_average,price_last,return
ticker,,,,,,,,
000660 KS,SK HYNIX INC,5500,8.983855e+08,9.300500e+08,31664513.0,163342.815818,169100.0,3.524602
003030 KS,SEAH STEEL HOLDINGS CORP,5999,1.078803e+09,1.027029e+09,-51774426.0,179830.509418,171200.0,-4.799246
006040 KS,DONGWON INDUSTRIES CO LTD,10000,3.127836e+08,3.105000e+08,-2283571.0,31278.357100,31050.0,-0.730080
007340 KS,DN AUTOMOTIVE CORP,29231,2.816697e+09,2.984485e+09,167787616.0,96359.942664,102100.0,5.956892
023160 KS,TK CORPORATION,40000,5.788190e+08,5.460000e+08,-32818951.0,14470.473775,13650.0,-5.669986
271560 KS,ORION CORP/REPUBLIC OF KOREA,21800,1.979422e+09,2.090620e+09,111197556.0,90799.194679,95900.0,5.617677
282690 KS,DONG AH TIRE & RUBBER CO LTD,2500,3.255249e+07,3.375000e+07,1197510.0,13020.996000,13500.0,3.678705
316140 KS,WOORI FINANCIAL GROUP INC,42500,6.692726e+08,6.570500e+08,-12222634.0,15747.591388,15460.0,-1.826256

In [17]:
get_price_of_date_by_ticker(ticker='000660 KS', date='2024-09-30')

174600