In [1]:
from cayman_office_system import *

INFO:shining_pebbles:Shining Pebbles package initialized
INFO:numexpr.utils:Note: NumExpr detected 10 cores but "NUMEXPR_MAX_THREADS" not set, so enforcing safe limit of 8.
INFO:numexpr.utils:NumExpr defaulting to 8 threads.

In [2]:
trades = Trades()

| import trade of (date, index) = (2024-09-02, None)
|- cash flow of trade: -614581438.0
| import trade of (date, index) = (2024-09-05, None)
|- cash flow of trade: -529470241.0
| import trade of (date, index) = (2024-09-06, None)
|- cash flow of trade: -91060069.0
| import trade of (date, index) = (2024-09-09, None)
|- cash flow of trade: -384482599.0
| import trade of (date, index) = (2024-09-10, None)
|- cash flow of trade: -625076151.0
| import trade of (date, index) = (2024-09-12, None)
|- cash flow of trade: -528686258.0
| import trade of (date, index) = (2024-09-13, None)
|- cash flow of trade: -519691172.0
| import trade of (date, index) = (2024-09-19, None)
|- cash flow of trade: -727234488.0
| import trade of (date, index) = (2024-09-20, None)
|- cash flow of trade: -1931465216.0
| import trade of (date, index) = (2024-09-23, None)
|- cash flow of trade: -726876600.0
| import trade of (date, index) = (2024-09-24, None)
|- cash flow of trade: -1282227226.0
| import trade of (date, index) = (2024-09-26, None)
|- cash flow of trade: -405884829.0
| import trade of (date, index) = (2024-10-08, None)
|- cash flow of trade: -670806496.0
| import trade of (date, index) = (2024-10-10, None)
|- cash flow of trade: -1479583697.0
| import trade of (date, index) = (2024-10-11, None)
|- cash flow of trade: -341436216.0
| import trade of (date, index) = (2024-10-15, None)
|- cash flow of trade: -871019390.0
| import trade of (date, index) = (2024-10-16, None)
|- cash flow of trade: 1136647412.0
| import trade of (date, index) = (2024-10-17, None)
|- cash flow of trade: -480907757.0
| import trade of (date, index) = (2024-10-21, None)
|- cash flow of trade: -635232077.0
| import trade of (date, index) = (2024-10-24, None)
|- cash flow of trade: -101252902.0
| append synthetic trade of Sell (date) = (2024-10-07)
|- cash flow of synthetic trade: 2984485100.0
| append synthetic trade of Sell (date) = (2024-10-07)
|- cash flow of synthetic trade: 33750000.0
| append synthetic trade of Buy (date) = (2024-10-08)
|- cash flow of synthetic trade: -2843520000.0

In [3]:
holdings = Holdings(trades=trades)

In [6]:
holdings.get_df_ref()

,name,num_shares,price_average,price_last,total_amount,valuation,pl
ticker,,,,,,,
271560 KS,ORION CORP/REPUBLIC OF KOREA,38300.0,94636.10,97900.0,3.624563e+09,3.749570e+09,125007370.0
007340 KS,DN AUTOMOTIVE CORP,197400.0,18188.98,18140.0,3.590505e+09,3.580836e+09,-9668652.0
316140 KS,WOORI FINANCIAL GROUP INC,115000.0,16056.51,16060.0,1.846499e+09,1.846900e+09,401350.0
003030 KS,SEAH STEEL HOLDINGS CORP,6090.0,179561.27,162900.0,1.093528e+09,9.920610e+08,-101467134.3
023160 KS,TK CORPORATION,60000.0,14283.07,12390.0,8.569842e+08,7.434000e+08,-113584200.0
006040 KS,DONGWON INDUSTRIES CO LTD,19000.0,32210.06,33850.0,6.119911e+08,6.431500e+08,31158860.0
375500 KS,DL E&C CO LTD,5000.0,31617.01,30700.0,1.580850e+08,1.535000e+08,-4585050.0
282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,0.00,13500.0,0.000000e+00,0.000000e+00,0.0
000660 KS,SK HYNIX INC,0.0,0.00,196000.0,0.000000e+00,0.000000e+00,0.0

In [8]:
df = holdings.get_df()
df

/Users/juneyoungpark/dev/module-cayman_office_system/cayman_office_system/holdings.py:43: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['return'] = (df['valuation'] / df['total_amount'] -1) * 100
/Users/juneyoungpark/dev/module-cayman_office_system/cayman_office_system/holdings.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weight'] = df['valuation'] / df_nav.iloc[0]['nav: krw'] * 100

,name,num_shares,price_average,price_last,total_amount,valuation,pl,return,weight
ticker,,,,,,,,,
271560 KS,ORION CORP/REPUBLIC OF KOREA,38300.0,94636.10,97900.0,3.624563e+09,3.749570e+09,125007370.0,3.448895,17.379396
007340 KS,DN AUTOMOTIVE CORP,197400.0,18188.98,18140.0,3.590505e+09,3.580836e+09,-9668652.0,-0.269284,16.597307
316140 KS,WOORI FINANCIAL GROUP INC,115000.0,16056.51,16060.0,1.846499e+09,1.846900e+09,401350.0,0.021736,8.560450
003030 KS,SEAH STEEL HOLDINGS CORP,6090.0,179561.27,162900.0,1.093528e+09,9.920610e+08,-101467134.3,-9.278877,4.598239
023160 KS,TK CORPORATION,60000.0,14283.07,12390.0,8.569842e+08,7.434000e+08,-113584200.0,-13.253943,3.445686
006040 KS,DONGWON INDUSTRIES CO LTD,19000.0,32210.06,33850.0,6.119911e+08,6.431500e+08,31158860.0,5.091391,2.981024
375500 KS,DL E&C CO LTD,5000.0,31617.01,30700.0,1.580850e+08,1.535000e+08,-4585050.0,-2.900369,0.711478

In [13]:
tickers_bbg = [get_ticker_bbg_of_ticker(ticker) for ticker in df.index]
tickers_bbg

['271560 KS Equity',
 '007340 KS Equity',
 '316140 KS Equity',
 '003030 KS Equity',
 '023160 KS Equity',
 '006040 KS Equity',
 '375500 KS Equity']

In [10]:
ks = get_ks_market_info()
ks

,name_kr,name,market_index,sector,cap(/1e8),price_last
ticker_bbg,,,,,,
000020 KS Equity,동화약품,DONGWHA PHARM CO LTD,KOSPI Index,Health Care,2092.0,7490.0
000040 KS Equity,KR모터스,KR MOTORS CO LTD,KOSPI Index,Consumer Discretionary,307.0,512.0
000050 KS Equity,경방,KYUNGBANG CO LTD,KOSPI Index,Consumer Discretionary,1729.0,6310.0
000070 KS Equity,삼양홀딩스,SAMYANG HOLDINGS CORP,KOSPI Index,Consumer Staples,6132.0,71600.0
000080 KS Equity,하이트진로,HITE JINRO CO LTD,KOSPI Index,Consumer Staples,14938.0,21300.0
...,...,...,...,...,...,...
950170 KS Equity,JTC,NaN,NaN,NaN,2029.0,4035.0
950190 KS Equity,미투젠,NaN,NaN,NaN,1405.0,10350.0
950200 KS Equity,소마젠,NaN,NaN,NaN,807.0,4200.0
950210 KS Equity,프레스티지바이오파마,NaN,NaN,NaN,2389.0,19880.0
950220 KS Equity,네오이뮨텍,NaN,NaN,NaN,287.0,1453.0

In [14]:
ks[ks.index.isin(tickers_bbg)]

,name_kr,name,market_index,sector,cap(/1e8),price_last
ticker_bbg,,,,,,
003030 KS Equity,세아제강지주,SEAH STEEL HOLDINGS CORP,KOSPI Index,Materials,6746.0,162900.0
006040 KS Equity,동원산업,DONGWON INDUSTRIES CO LTD,KOSPI Index,Consumer Staples,12193.0,33850.0
007340 KS Equity,DN오토모티브,DN AUTOMOTIVE CORP,KOSPI Index,Consumer Discretionary,10986.0,18140.0
023160 KS Equity,태광,TK CORPORATION,KOSDAQ Index,Industrials,3283.0,12390.0
271560 KS Equity,오리온,ORION CORP/REPUBLIC OF KOREA,KOSPI Index,Consumer Staples,38705.0,97900.0
316140 KS Equity,우리금융지주,WOORI FINANCIAL GROUP INC,KOSPI Index,Financials,119260.0,16060.0
375500 KS Equity,DL이앤씨,DL E&C CO LTD,KOSPI Index,Industrials,11878.0,30700.0

In [ ]:
df

In [35]:
df_nav = holdings.ts.df
df_nav = df_nav[df_nav.index == holdings.date]
df_nav

,cash: usd,cash: krw,stock: usd,stock: krw,nav: usd,nav: krw,weight_cash,weight_stock,usdkrw
date,,,,,,,,,
2024-10-28,7.120707e+06,9.865384e+09,8.451707e+06,1.170942e+10,1.557241e+07,2.157480e+10,45.726419,54.273581,1385.45

In [37]:
df = holdings.get_df().copy()
df = df[df['num_shares_cum'] != 0]
df['return'] = (df['valuation'] / df['total_amount'] -1) * 100
df['weight'] = df['valuation'] / df_nav.iloc[0]['nav: krw'] * 100
# df['attribution'] = df['weight'] * df['return'] / 100
df

,name,num_shares_cum,price_average,price_last,total_amount,valuation,pl,return,weight
ticker,,,,,,,,,
271560 KS,ORION CORP/REPUBLIC OF KOREA,38300.0,94636.10,97900.0,3.624563e+09,3.749570e+09,125007370.0,3.448895,17.379396
007340 KS,DN AUTOMOTIVE CORP,197400.0,18188.98,18140.0,3.590505e+09,3.580836e+09,-9668652.0,-0.269284,16.597307
316140 KS,WOORI FINANCIAL GROUP INC,115000.0,16056.51,16060.0,1.846499e+09,1.846900e+09,401350.0,0.021736,8.560450
003030 KS,SEAH STEEL HOLDINGS CORP,6090.0,179561.27,162900.0,1.093528e+09,9.920610e+08,-101467134.3,-9.278877,4.598239
023160 KS,TK CORPORATION,60000.0,14283.07,12390.0,8.569842e+08,7.434000e+08,-113584200.0,-13.253943,3.445686
006040 KS,DONGWON INDUSTRIES CO LTD,19000.0,32210.06,33850.0,6.119911e+08,6.431500e+08,31158860.0,5.091391,2.981024
375500 KS,DL E&C CO LTD,5000.0,31617.01,30700.0,1.580850e+08,1.535000e+08,-4585050.0,-2.900369,0.711478

In [39]:
df['total_amount'].sum() , df['valuation'].sum()

(11782154456.3, 11709417000.0)

In [22]:
holdings.date

'2024-10-28'

In [23]:
df_nav = holdings.ts.df
df_nav = df_nav[df_nav.index == holdings.date]
df_nav

,cash: usd,cash: krw,stock: usd,stock: krw,nav: usd,nav: krw,weight_cash,weight_stock,usdkrw
date,,,,,,,,,
2024-10-28,7.120707e+06,9.865384e+09,8.451707e+06,1.170942e+10,1.557241e+07,2.157480e+10,45.726419,54.273581,1385.45

In [25]:
df['weight'] = df['valuation'] / df_nav.iloc[0]['nav: krw'] * 100
df['attribution'] = df['weight'] * df['return'] / 100
df

,name,num_shares_cum,price_average,price_last,total_amount,valuation,pl,return,weight,attribution
ticker,,,,,,,,,,
271560 KS,ORION CORP/REPUBLIC OF KOREA,38300.0,94636.10,97900.0,3.624563e+09,3.749570e+09,125007370.0,3.448895,17.379396,0.599397
007340 KS,DN AUTOMOTIVE CORP,197400.0,18188.98,18140.0,3.590505e+09,3.580836e+09,-9668652.0,-0.269284,16.597307,-0.044694
316140 KS,WOORI FINANCIAL GROUP INC,115000.0,16056.51,16060.0,1.846499e+09,1.846900e+09,401350.0,0.021736,8.560450,0.001861
003030 KS,SEAH STEEL HOLDINGS CORP,6090.0,179561.27,162900.0,1.093528e+09,9.920610e+08,-101467134.3,-9.278877,4.598239,-0.426665
023160 KS,TK CORPORATION,60000.0,14283.07,12390.0,8.569842e+08,7.434000e+08,-113584200.0,-13.253943,3.445686,-0.456689
006040 KS,DONGWON INDUSTRIES CO LTD,19000.0,32210.06,33850.0,6.119911e+08,6.431500e+08,31158860.0,5.091391,2.981024,0.151776
375500 KS,DL E&C CO LTD,5000.0,31617.01,30700.0,1.580850e+08,1.535000e+08,-4585050.0,-2.900369,0.711478,-0.020635

In [34]:
(30700.0	/ 31617.01 -1 ) * 100 , 1.535000e+08 / 2.157480e+10 * 100

(-2.9003691367399997, 0.7114782060552126)

In [26]:
df['attribution'].sum()

-0.19565028991236535

In [27]:
df['weight'].sum()

54.27358074901284

In [30]:
holdings.ts.get_timeseries_nav()

,nav: usd,nav: krw,return: usd,return: krw,cumreturn: usd,cumreturn: krw,usdkrw
date,,,,,,,
2024-09-01,1.578991e+07,2.112374e+10,0.000000,0.000000,0.000000,0.000000,1337.80
2024-09-02,1.578924e+07,2.113153e+10,-0.004218,0.036892,-0.004218,0.036892,1338.35
2024-09-03,1.579731e+07,2.119841e+10,0.051078,0.316465,0.046857,0.353474,1341.90
2024-09-04,1.578936e+07,2.108669e+10,-0.050308,-0.527004,-0.003475,-0.175393,1335.50
2024-09-05,1.579425e+07,2.107822e+10,0.030968,-0.040188,0.027492,-0.215511,1334.55
2024-09-06,1.578732e+07,2.107608e+10,-0.043856,-0.010152,-0.016376,-0.225640,1335.00
2024-09-07,1.578732e+07,2.107608e+10,0.000000,0.000000,-0.016376,-0.225640,1335.00
2024-09-08,1.578732e+07,2.107608e+10,0.000000,0.000000,-0.016376,-0.225640,1335.00
2024-09-09,1.579941e+07,2.120280e+10,0.076542,0.601288,0.060153,0.374291,1342.00
2024-09-10,1.575146e+07,2.116996e+10,-0.303469,-0.154890,-0.243498,0.218821,1344.00
2024-09-11,1.577324e+07,2.114087e+10,0.138250,-0.137428,-0.105584,0.081092,1340.30
2024-09-12,1.582266e+07,2.123401e+10,0.313348,0.440582,0.207432,0.522032,1342.00
2024-09-13,1.580290e+07,2.107396e+10,-0.124889,-0.753760,0.082284,-0.235663,1333.55
2024-09-14,1.580290e+07,2.107396e+10,0.000000,0.000000,0.082284,-0.235663,1333.55
2024-09-15,1.580290e+07,2.107396e+10,0.000000,0.000000,0.082284,-0.235663,1333.55
2024-09-16,1.580290e+07,2.107396e+10,0.000000,0.000000,0.082284,-0.235663,1333.55
2024-09-17,1.580290e+07,2.107396e+10,0.000000,0.000000,0.082284,-0.235663,1333.55
2024-09-18,1.580290e+07,2.107396e+10,0.000000,0.000000,0.082284,-0.235663,1333.55
2024-09-19,1.585040e+07,2.106597e+10,0.300554,-0.037906,0.383085,-0.273479,1329.05
2024-09-20,1.594940e+07,2.129564e+10,0.624617,1.090244,1.010095,0.813783,1335.20
2024-09-21,1.594940e+07,2.129564e+10,0.000000,0.000000,1.010095,0.813783,1335.20
2024-09-22,1.594940e+07,2.129564e+10,0.000000,0.000000,1.010095,0.813783,1335.20
2024-09-23,1.597251e+07,2.132729e+10,0.144867,0.148617,1.156426,0.963610,1335.25
2024-09-24,1.602804e+07,2.133813e+10,0.347665,0.050811,1.508111,1.014911,1331.30
2024-09-25,1.600216e+07,2.137089e+10,-0.161425,0.153547,1.344252,1.170017,1335.50
2024-09-26,1.621707e+07,2.136356e+10,1.342998,-0.034295,2.705303,1.135320,1317.35
2024-09-27,1.626408e+07,2.131490e+10,0.289888,-0.227796,3.003034,0.904938,1310.55
2024-09-28,1.626408e+07,2.131490e+10,0.000000,0.000000,3.003034,0.904938,1310.55
2024-09-29,1.626408e+07,2.131490e+10,0.000000,0.000000,3.003034,0.904938,1310.55
2024-09-30,1.611138e+07,2.118164e+10,-0.938889,-0.625201,2.035949,0.274079,1314.70
2024-10-01,1.611138e+07,2.118164e+10,0.000000,0.000000,2.035949,0.274079,1314.70
2024-10-02,1.600624e+07,2.117546e+10,-0.652590,-0.029165,1.370073,0.244833,1322.95
2024-10-03,1.600624e+07,2.117546e+10,0.000000,0.000000,1.370073,0.244833,1322.95
2024-10-04,1.592985e+07,2.147663e+10,-0.477241,1.422264,0.886294,1.670580,1348.20
2024-10-05,1.592985e+07,2.147663e+10,0.000000,0.000000,0.886294,1.670580,1348.20
2024-10-06,1.592985e+07,2.147663e+10,0.000000,0.000000,0.886294,1.670580,1348.20
2024-10-07,1.602025e+07,2.153522e+10,0.567464,0.272819,1.458788,1.947956,1344.25
2024-10-08,1.599535e+07,2.153454e+10,-0.155448,-0.003183,1.301072,1.944711,1346.30
2024-10-09,1.599535e+07,2.153454e+10,0.000000,0.000000,1.301072,1.944711,1346.30
2024-10-10,1.599691e+07,2.165982e+10,0.009797,0.581791,1.310997,2.537816,1354.00
2024-10-11,1.593656e+07,2.152949e+10,-0.377298,-0.601707,0.928752,1.920838,1350.95
2024-10-12,1.593656e+07,2.152949e+10,0.000000,0.000000,0.928752,1.920838,1350.95
2024-10-13,1.593656e+07,2.152949e+10,0.000000,0.000000,0.928752,1.920838,1350.95
2024-10-14,1.599376e+07,2.171632e+10,0.358916,0.867786,1.291001,2.805293,1357.80
2024-10-15,1.598559e+07,2.181714e+10,-0.051041,0.464236,1.239301,3.282552,1364.80
2024-10-16,1.587793e+07,2.166623e+10,-0.673494,-0.691689,0.557460,2.568158,1364.55
2024-10-17,1.588075e+07,2.179632e+10,0.017732,0.600445,0.575291,3.184024,1372.50
2024-10-18,1.584169e+07,2.168411e+10,-0.245906,-0.514824,0.327971,2.652808,1368.80
2024-10-19,1.584169e+07,2.168411e+10,0.000000,0.000000,0.327971,2.652808,1368.80
2024-10-20,1.584169e+07,2.168411e+10,0.000000,0.000000,0.327971,2.652808,1368.80
2024-10-21,1.568248e+07,2.161360e+10,-1.005007,-0.325175,-0.680332,2.319006,1378.20
2024-10-22,1.558495e+07,2.146515e+10,-0.621939,-0.686836,-1.298040,1.616243,1377.30
2024-10-23,1.554108e+07,2.148244e+10,-0.281471,0.080536,-1.575857,1.698081,1382.30
2024-10-24,1.561959e+07,2.156363e+10,0.505176,0.377936,-1.078642,2.082434,1380.55
2024-10-25,1.549065e+07,2.153355e+10,-0.825533,-0.139491,-1.895271,1.940039,1390.10
2024-10-26,1.549065e+07,2.153355e+10,0.000000,0.000000,-1.895271,1.940039,1390.10
2024-10-27,1.549065e+07,2.153355e+10,0.000000,0.000000,-1.895271,1.940039,1390.10
2024-10-28,1.557241e+07,2.157480e+10,0.527848,0.191574,-1.377427,2.135329,1385.45

In [6]:
holdings.stocks[3].timeseries

,date,ticker,name,num_shares_cum,price_trade,price_average,total_amount,realization,price_last,valuation,pl
0,2024-09-02,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
1,2024-09-03,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
2,2024-09-04,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
3,2024-09-05,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
4,2024-09-06,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
5,2024-09-07,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
6,2024-09-08,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
7,2024-09-09,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
8,2024-09-10,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
9,2024-09-11,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
10,2024-09-12,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
11,2024-09-13,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
12,2024-09-14,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
13,2024-09-15,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
14,2024-09-16,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
15,2024-09-17,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
16,2024-09-18,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
17,2024-09-19,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
18,2024-09-20,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
19,2024-09-21,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
20,2024-09-22,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
21,2024-09-23,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
22,2024-09-24,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
23,2024-09-25,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
24,2024-09-26,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
25,2024-09-27,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
26,2024-09-28,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
27,2024-09-29,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
28,2024-09-30,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
29,2024-10-01,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
30,2024-10-02,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
31,2024-10-03,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
32,2024-10-04,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
33,2024-10-05,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
34,2024-10-06,282690 KS,DONG AH TIRE & RUBBER CO LTD,2500.0,13007.988,13021.0,32552500.0,0.0,13500.0,33750000.0,1197500.0
35,2024-10-07,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,33750000.0,13500.0,0.0,0.0
36,2024-10-08,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
37,2024-10-09,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
38,2024-10-10,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
39,2024-10-11,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
40,2024-10-12,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
41,2024-10-13,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
42,2024-10-14,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
43,2024-10-15,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
44,2024-10-16,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
45,2024-10-17,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
46,2024-10-18,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
47,2024-10-19,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
48,2024-10-20,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
49,2024-10-21,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
50,2024-10-22,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
51,2024-10-23,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
52,2024-10-24,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
53,2024-10-25,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
54,2024-10-26,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
55,2024-10-27,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0
56,2024-10-28,282690 KS,DONG AH TIRE & RUBBER CO LTD,0.0,13500.000,0.0,0.0,0.0,13500.0,0.0,0.0

In [3]:
df = trades.df
df

,date,ticker,name,type,num_shares,price_trade,amount_trade,delta_shares,cashflow
0,2024-09-02,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,900,177645.666667,160040981.0,900,-160040981.0
1,2024-09-02,007340 KS,DN AUTOMOTIVE CORP,Buy,2500,88110.280000,220495976.0,2500,-220495976.0
2,2024-09-02,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,2200,91495.772727,201491991.0,2200,-201491991.0
3,2024-09-02,282690 KS,DONG AH TIRE & RUBBER CO LTD,Buy,2500,13007.988000,32552490.0,2500,-32552490.0
4,2024-09-05,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,800,175209.750000,140307968.0,800,-140307968.0
...,...,...,...,...,...,...,...,...,...
81,2024-10-21,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,3000,99952.333333,300156857.0,3000,-300156857.0
82,2024-10-21,375500 KS,DL E&C CO LTD,Buy,5000,31585.420000,158085027.0,5000,-158085027.0
83,2024-10-24,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,91,161650.549451,14724910.0,91,-14724910.0
84,2024-10-24,007340 KS,DN AUTOMOTIVE CORP,Buy,2400,17476.937500,41986595.0,2400,-41986595.0
85,2024-10-24,271560 KS,ORION CORP/REPUBLIC OF KOREA,Buy,450,98882.000000,44541397.0,450,-44541397.0

In [4]:
df_stock = trades.dfs[trades.tickers[0]]
df_stock

,date,ticker,name,type,num_shares,price_trade,amount_trade,delta_shares,cashflow,cashflow_cum,num_shares_cum,price_average
0,2024-09-02,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,900,177645.666667,160040981.0,900,-160040981.0,-1.600410e+08,900,177823.31
1,2024-09-05,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,800,175209.750000,140307968.0,800,-140307968.0,-3.003489e+08,1700,176675.85
2,2024-09-09,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,500,174271.000000,87222636.0,500,-87222636.0,-3.875716e+08,2200,176168.90
3,2024-09-10,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,200,167672.000000,33567934.0,200,-33567934.0,-4.211395e+08,2400,175474.80
4,2024-09-12,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,350,174357.714286,61086225.0,350,-61086225.0,-4.822257e+08,2750,175354.82
5,2024-09-13,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,350,171938.857143,60238779.0,350,-60238779.0,-5.424645e+08,3100,174988.56
6,2024-09-19,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,699,179751.359084,125771846.0,699,-125771846.0,-6.682364e+08,3799,175897.96
7,2024-09-20,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,1200,185050.583333,222282761.0,1200,-222282761.0,-8.905191e+08,4999,178139.45
8,2024-09-23,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,250,184116.400000,46075129.0,250,-46075129.0,-9.365943e+08,5249,178432.89
9,2024-09-24,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,500,189070.400000,94629735.0,500,-94629735.0,-1.031224e+09,5749,179374.50
10,2024-09-26,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,250,190126.800000,47579232.0,250,-47579232.0,-1.078803e+09,5999,179830.51
11,2024-10-24,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,91,161650.549451,14724910.0,91,-14724910.0,-1.093528e+09,6090,179561.27

In [7]:
df_stock = trades.dfs[trades.tickers[1]]
stock = Stock(df=df_stock)
stock

In [12]:
stock.timeseries

,date,ticker,name,num_shares_cum,price_trade,price_average,total_amount,realization,price_last,valuation,pl
0,2024-09-02,007340 KS,DN AUTOMOTIVE CORP,2500.0,88110.280000,88198.39,2.204960e+08,0.000000e+00,88200.0,2.205000e+08,4.025000e+03
1,2024-09-03,007340 KS,DN AUTOMOTIVE CORP,2500.0,88110.280000,88198.39,2.204960e+08,0.000000e+00,92500.0,2.312500e+08,1.075402e+07
2,2024-09-04,007340 KS,DN AUTOMOTIVE CORP,2500.0,88110.280000,88198.39,2.204960e+08,0.000000e+00,90100.0,2.252500e+08,4.754025e+06
3,2024-09-05,007340 KS,DN AUTOMOTIVE CORP,5000.0,91637.240000,89963.63,4.498182e+08,0.000000e+00,91900.0,4.595000e+08,9.681850e+06
4,2024-09-06,007340 KS,DN AUTOMOTIVE CORP,6000.0,90969.100000,90146.37,5.408782e+08,0.000000e+00,90400.0,5.424000e+08,1.521780e+06
5,2024-09-07,007340 KS,DN AUTOMOTIVE CORP,6000.0,90969.100000,90146.37,5.408782e+08,0.000000e+00,90400.0,5.424000e+08,1.521780e+06
6,2024-09-08,007340 KS,DN AUTOMOTIVE CORP,6000.0,90969.100000,90146.37,5.408782e+08,0.000000e+00,90400.0,5.424000e+08,1.521780e+06
7,2024-09-09,007340 KS,DN AUTOMOTIVE CORP,8231.0,93556.611385,91096.07,7.498118e+08,0.000000e+00,94200.0,7.753602e+08,2.554845e+07
8,2024-09-10,007340 KS,DN AUTOMOTIVE CORP,11731.0,90417.457143,90920.58,1.066589e+09,0.000000e+00,89900.0,1.054617e+09,-1.197242e+07
9,2024-09-11,007340 KS,DN AUTOMOTIVE CORP,11731.0,90417.457143,90920.58,1.066589e+09,0.000000e+00,91800.0,1.076906e+09,1.031648e+07
10,2024-09-12,007340 KS,DN AUTOMOTIVE CORP,13231.0,92685.933333,91131.23,1.205757e+09,0.000000e+00,93900.0,1.242391e+09,3.663360e+07
11,2024-09-13,007340 KS,DN AUTOMOTIVE CORP,14731.0,92786.400000,91309.21,1.345076e+09,0.000000e+00,92400.0,1.361144e+09,1.606843e+07
12,2024-09-14,007340 KS,DN AUTOMOTIVE CORP,14731.0,92786.400000,91309.21,1.345076e+09,0.000000e+00,92400.0,1.361144e+09,1.606843e+07
13,2024-09-15,007340 KS,DN AUTOMOTIVE CORP,14731.0,92786.400000,91309.21,1.345076e+09,0.000000e+00,92400.0,1.361144e+09,1.606843e+07
14,2024-09-16,007340 KS,DN AUTOMOTIVE CORP,14731.0,92786.400000,91309.21,1.345076e+09,0.000000e+00,92400.0,1.361144e+09,1.606843e+07
15,2024-09-17,007340 KS,DN AUTOMOTIVE CORP,14731.0,92786.400000,91309.21,1.345076e+09,0.000000e+00,92400.0,1.361144e+09,1.606843e+07
16,2024-09-18,007340 KS,DN AUTOMOTIVE CORP,14731.0,92786.400000,91309.21,1.345076e+09,0.000000e+00,92400.0,1.361144e+09,1.606843e+07
17,2024-09-19,007340 KS,DN AUTOMOTIVE CORP,16231.0,95794.600000,91732.59,1.488912e+09,0.000000e+00,95900.0,1.556553e+09,6.764123e+07
18,2024-09-20,007340 KS,DN AUTOMOTIVE CORP,20731.0,102093.444444,94003.74,1.948792e+09,0.000000e+00,102200.0,2.118708e+09,1.699167e+08
19,2024-09-21,007340 KS,DN AUTOMOTIVE CORP,20731.0,102093.444444,94003.74,1.948792e+09,0.000000e+00,102200.0,2.118708e+09,1.699167e+08
20,2024-09-22,007340 KS,DN AUTOMOTIVE CORP,20731.0,102093.444444,94003.74,1.948792e+09,0.000000e+00,102200.0,2.118708e+09,1.699167e+08
21,2024-09-23,007340 KS,DN AUTOMOTIVE CORP,22731.0,100705.900000,94602.29,2.150405e+09,0.000000e+00,101200.0,2.300377e+09,1.499725e+08
22,2024-09-24,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
23,2024-09-25,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
24,2024-09-26,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
25,2024-09-27,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
26,2024-09-28,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
27,2024-09-29,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
28,2024-09-30,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
29,2024-10-01,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
30,2024-10-02,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
31,2024-10-03,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
32,2024-10-04,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
33,2024-10-05,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
34,2024-10-06,007340 KS,DN AUTOMOTIVE CORP,29231.0,102404.169231,96359.94,2.816697e+09,0.000000e+00,102100.0,2.984485e+09,1.677877e+08
35,2024-10-07,007340 KS,DN AUTOMOTIVE CORP,0.0,102100.000000,0.00,0.000000e+00,2.984485e+09,102100.0,0.000000e+00,0.000000e+00
36,2024-10-08,007340 KS,DN AUTOMOTIVE CORP,148100.0,19200.000000,18067.07,2.675733e+09,0.000000e+00,19200.0,2.843520e+09,1.677869e+08
37,2024-10-08,007340 KS,DN AUTOMOTIVE CORP,156100.0,18989.843750,18115.33,2.827803e+09,0.000000e+00,19200.0,2.997120e+09,1.693170e+08
38,2024-10-09,007340 KS,DN AUTOMOTIVE CORP,156100.0,18989.843750,18115.33,2.827803e+09,0.000000e+00,19200.0,2.997120e+09,1.693170e+08
39,2024-10-10,007340 KS,DN AUTOMOTIVE CORP,164245.0,18878.147330,18154.09,2.981719e+09,0.000000e+00,18680.0,3.068097e+09,8.637809e+07
40,2024-10-11,007340 KS,DN AUTOMOTIVE CORP,169245.0,18529.124000,18165.72,3.074457e+09,0.000000e+00,18650.0,3.156419e+09,8.196197e+07
41,2024-10-12,007340 KS,DN AUTOMOTIVE CORP,169245.0,18529.124000,18165.72,3.074457e+09,0.000000e+00,18650.0,3.156419e+09,8.196197e+07
42,2024-10-13,007340 KS,DN AUTOMOTIVE CORP,169245.0,18529.124000,18165.72,3.074457e+09,0.000000e+00,18650.0,3.156419e+09,8.196197e+07
43,2024-10-14,007340 KS,DN AUTOMOTIVE CORP,169245.0,18529.124000,18165.72,3.074457e+09,0.000000e+00,18790.0,3.180114e+09,1.056563e+08
44,2024-10-15,007340 KS,DN AUTOMOTIVE CORP,181000.0,18917.456402,18215.77,3.297054e+09,0.000000e+00,18840.0,3.410040e+09,1.129856e+08
45,2024-10-16,007340 KS,DN AUTOMOTIVE CORP,181000.0,18917.456402,18215.77,3.297054e+09,0.000000e+00,18300.0,3.312300e+09,1.524563e+07
46,2024-10-17,007340 KS,DN AUTOMOTIVE CORP,185000.0,18599.455000,18224.47,3.371527e+09,0.000000e+00,18670.0,3.453950e+09,8.242305e+07
47,2024-10-18,007340 KS,DN AUTOMOTIVE CORP,185000.0,18599.455000,18224.47,3.371527e+09,0.000000e+00,18060.0,3.341100e+09,-3.042695e+07
48,2024-10-19,007340 KS,DN AUTOMOTIVE CORP,185000.0,18599.455000,18224.47,3.371527e+09,0.000000e+00,18060.0,3.341100e+09,-3.042695e+07
49,2024-10-20,007340 KS,DN AUTOMOTIVE CORP,185000.0,18599.455000,18224.47,3.371527e+09,0.000000e+00,18060.0,3.341100e+09,-3.042695e+07
50,2024-10-21,007340 KS,DN AUTOMOTIVE CORP,195000.0,17681.338000,18197.52,3.548516e+09,0.000000e+00,17680.0,3.447600e+09,-1.009164e+08
51,2024-10-22,007340 KS,DN AUTOMOTIVE CORP,195000.0,17681.338000,18197.52,3.548516e+09,0.000000e+00,17410.0,3.394950e+09,-1.535664e+08
52,2024-10-23,007340 KS,DN AUTOMOTIVE CORP,195000.0,17681.338000,18197.52,3.548516e+09,0.000000e+00,17590.0,3.430050e+09,-1.184664e+08
53,2024-10-24,007340 KS,DN AUTOMOTIVE CORP,197400.0,17476.937500,18188.98,3.590505e+09,0.000000e+00,17610.0,3.476214e+09,-1.142907e+08
54,2024-10-25,007340 KS,DN AUTOMOTIVE CORP,197400.0,17476.937500,18188.98,3.590505e+09,0.000000e+00,17590.0,3.472266e+09,-1.182387e+08
55,2024-10-26,007340 KS,DN AUTOMOTIVE CORP,197400.0,17476.937500,18188.98,3.590505e+09,0.000000e+00,17590.0,3.472266e+09,-1.182387e+08
56,2024-10-27,007340 KS,DN AUTOMOTIVE CORP,197400.0,17476.937500,18188.98,3.590505e+09,0.000000e+00,17590.0,3.472266e+09,-1.182387e+08
57,2024-10-28,007340 KS,DN AUTOMOTIVE CORP,197400.0,17476.937500,18188.98,3.590505e+09,0.000000e+00,18140.0,3.580836e+09,-9.668652e+06

In [8]:
stock.get_number()

            num_shares: 007340 KS
date
2024-09-02                   2500
2024-09-03                   2500
2024-09-04                   2500
2024-09-05                   5000
2024-09-06                   6000
2024-09-07                   6000
2024-09-08                   6000
2024-09-09                   8231
2024-09-10                  11731
2024-09-11                  11731
2024-09-12                  13231
2024-09-13                  14731
2024-09-14                  14731
2024-09-15                  14731
2024-09-16                  14731
2024-09-17                  14731
2024-09-18                  14731
2024-09-19                  16231
2024-09-20                  20731
2024-09-21                  20731
2024-09-22                  20731
2024-09-23                  22731
2024-09-24                  29231
2024-09-25                  29231
2024-09-26                  29231
2024-09-27                  29231
2024-09-28                  29231
2024-09-29                  29231
2024-09-30                  29231
2024-10-01                  29231
2024-10-02                  29231
2024-10-03                  29231
2024-10-04                  29231
2024-10-05                  29231
2024-10-06                  29231
2024-10-07                      0
2024-10-08                 156100
2024-10-09                 156100
2024-10-10                 164245
2024-10-11                 169245
2024-10-12                 169245
2024-10-13                 169245
2024-10-14                 169245
2024-10-15                 181000
2024-10-16                 181000
2024-10-17                 185000
2024-10-18                 185000
2024-10-19                 185000
2024-10-20                 185000
2024-10-21                 195000
2024-10-22                 195000
2024-10-23                 195000
2024-10-24                 197400
2024-10-25                 197400
2024-10-26                 197400
2024-10-27                 197400
2024-10-28                 197400

In [18]:
stock.df

,date,ticker,name,type,num_shares,price_trade,amount_trade,delta_shares,cashflow,cashflow_cum,num_shares_cum,price_average
0,2024-09-02,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,900,177645.666667,160040981.0,900,-160040981.0,-1.600410e+08,900,177823.31
1,2024-09-05,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,800,175209.750000,140307968.0,800,-140307968.0,-3.003489e+08,1700,176675.85
2,2024-09-09,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,500,174271.000000,87222636.0,500,-87222636.0,-3.875716e+08,2200,176168.90
3,2024-09-10,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,200,167672.000000,33567934.0,200,-33567934.0,-4.211395e+08,2400,175474.80
4,2024-09-12,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,350,174357.714286,61086225.0,350,-61086225.0,-4.822257e+08,2750,175354.82
5,2024-09-13,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,350,171938.857143,60238779.0,350,-60238779.0,-5.424645e+08,3100,174988.56
6,2024-09-19,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,699,179751.359084,125771846.0,699,-125771846.0,-6.682364e+08,3799,175897.96
7,2024-09-20,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,1200,185050.583333,222282761.0,1200,-222282761.0,-8.905191e+08,4999,178139.45
8,2024-09-23,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,250,184116.400000,46075129.0,250,-46075129.0,-9.365943e+08,5249,178432.89
9,2024-09-24,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,500,189070.400000,94629735.0,500,-94629735.0,-1.031224e+09,5749,179374.50
10,2024-09-26,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,250,190126.800000,47579232.0,250,-47579232.0,-1.078803e+09,5999,179830.51
11,2024-10-24,003030 KS,SEAH STEEL HOLDINGS CORP,Buy,91,161650.549451,14724910.0,91,-14724910.0,-1.093528e+09,6090,179561.27

In [20]:
stock.valuation

            valuation: 003030 KS
date
2024-09-02          1.585800e+08
2024-09-03          1.638000e+08
2024-09-04          1.584000e+08
2024-09-05          3.000500e+08
2024-09-06          3.017500e+08
2024-09-07          3.017500e+08
2024-09-08          3.017500e+08
2024-09-09          3.843400e+08
2024-09-10          4.017600e+08
2024-09-11          4.005600e+08
2024-09-12          4.801500e+08
2024-09-13          5.328900e+08
2024-09-14          5.328900e+08
2024-09-15          5.328900e+08
2024-09-16          5.328900e+08
2024-09-17          5.328900e+08
2024-09-18          5.328900e+08
2024-09-19          6.838200e+08
2024-09-20          9.348130e+08
2024-09-21          9.348130e+08
2024-09-22          9.348130e+08
2024-09-23          9.563678e+08
2024-09-24          1.099784e+09
2024-09-25          1.063565e+09
2024-09-26          1.132611e+09
2024-09-27          1.082820e+09
2024-09-28          1.082820e+09
2024-09-29          1.082820e+09
2024-09-30          1.045026e+09
2024-10-01          1.045026e+09
2024-10-02          1.027029e+09
2024-10-03          1.027029e+09
2024-10-04          1.042026e+09
2024-10-05          1.042026e+09
2024-10-06          1.042026e+09
2024-10-07          1.037827e+09
2024-10-08          1.039027e+09
2024-10-09          1.039027e+09
2024-10-10          1.030628e+09
2024-10-11          1.012631e+09
2024-10-12          1.012631e+09
2024-10-13          1.012631e+09
2024-10-14          1.008432e+09
2024-10-15          1.000033e+09
2024-10-16          9.760373e+08
2024-10-17          9.820363e+08
2024-10-18          1.007832e+09
2024-10-19          1.007832e+09
2024-10-20          1.007832e+09
2024-10-21          9.838360e+08
2024-10-22          9.556407e+08
2024-10-23          9.736377e+08
2024-10-24          9.920610e+08
2024-10-25          9.640470e+08
2024-10-26          9.640470e+08
2024-10-27          9.640470e+08
2024-10-28          9.920610e+08

In [12]:
ts = Timeseries(trades)
ts.valuation

            total_valuation
date
2024-09-02     6.136900e+08
2024-09-03     6.261400e+08
2024-09-04     6.125400e+08
2024-09-05     1.148100e+09
2024-09-06     1.230300e+09
2024-09-07     1.230300e+09
2024-09-08     1.230300e+09
2024-09-09     1.637450e+09
2024-09-10     2.200527e+09
2024-09-11     2.223656e+09
2024-09-12     2.821491e+09
2024-09-13     3.297064e+09
2024-09-14     3.297064e+09
2024-09-15     3.297064e+09
2024-09-16     3.297064e+09
2024-09-17     3.297064e+09
2024-09-18     3.297064e+09
2024-09-19     4.076298e+09
2024-09-20     6.158816e+09
2024-09-21     6.158816e+09
2024-09-22     6.158816e+09
2024-09-23     6.916775e+09
2024-09-24     8.252469e+09
2024-09-25     8.243950e+09
2024-09-26     8.820906e+09
2024-09-27     8.836985e+09
2024-09-28     8.836985e+09
2024-09-29     8.836985e+09
2024-09-30     8.664211e+09
2024-10-01     8.664211e+09
2024-10-02     8.579484e+09
2024-10-03     8.579484e+09
2024-10-04     8.640246e+09
2024-10-05     8.640246e+09
2024-10-06     8.640246e+09
2024-10-07     5.718212e+09
2024-10-08     9.207732e+09
2024-10-09     9.207732e+09
2024-10-10     1.074210e+10
2024-10-11     1.097780e+10
2024-10-12     1.097780e+10
2024-10-13     1.097780e+10
2024-10-14     1.111113e+10
2024-10-15     1.202829e+10
2024-10-16     1.074253e+10
2024-10-17     1.128989e+10
2024-10-18     1.120600e+10
2024-10-19     1.120600e+10
2024-10-20     1.120600e+10
2024-10-21     1.169876e+10
2024-10-22     1.155679e+10
2024-10-23     1.153810e+10
2024-10-24     1.173314e+10
2024-10-25     1.163505e+10
2024-10-26     1.163505e+10
2024-10-27     1.163505e+10
2024-10-28     1.170942e+10